# Site settings
title:          Declan Woodham
description:    "Personal ramblings, encounters and write ups within Cyber Security, Malware Analysis, and Reverse Engineering"
url:            https://declan.xyz

# Author
author:
  about: >
    Hi! I am a final year BSc Ethical Hacking student at The University of Abertay, Dundee. Here you can find my personal ramblings, encounters, and writeups within Cyber Security, Exploit Development and Reverse Engineering.

  name:         Declan Woodham
  email:        email@declan.xyz
  url:          https://declan.xyz


# Social
social:
  email: email@declan.xyz
  github: https://github.com/notdeclan
  linkedin: https://www.linkedin.com/in/declanwoodham/
  resume: /resume

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:      /:day-:month-:year/:title
paginate:       5
paginate_path: /:num

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2
