# Site settings
title:          Declan Woodham
description:    "Rain is a simple and clean Jekyll theme with focus on content."
url:            https://declan.xyz

# Author
author:
  name:         Declan Woodham
  email:        email@declan.xyz
  url:          https://declan.xyz


# Social
social:
  email: email@declan.xyz
  github: https://github.com/notdeclan
  linkedin: https://www.linkedin.com/in/declanwoodham/
  resume: /resume

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
paginate_path: /:num

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2
