title: Declan Woodham
author: Declan Woodham

email: email@declan.xyz
github: notdeclan
linkedin: declanwoodham

description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-minifier

sass:
  style: compressed
  sass_dir: _sass